"""
scaffold.py

Tool: ki_init_project
Creates .ki-base/ structure in a target project directory,
then registers the project in the global KI registry.

Created structure:
  <project_root>/
  └── .ki-base/
      ├── config.json        ← machine-specific (added to .gitignore)
      ├── ki_config.json     ← project settings (in git)
      ├── doc_config.json    ← file→KI mapping (in git)
      ├── AGENTS.md          ← instructions for AI agents (in git)
      ├── DIR_INDEX.md       ← directory index (in git)
      └── knowledge/
          └── _OVERVIEW.ki.md  ← starter KI (in git)
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Allow import of ki_utils from sibling scripts/ directory
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts"))
import ki_utils


# ─── Templates ────────────────────────────────────────────────────────────────

KI_CONFIG_TEMPLATE = {
    "project_name": "{project_name}",
    "language": "{language}",
    "doc_style": "ki-v2",
    "auto_resolve": True,
    "paths": {
        "knowledge_root": ".ki-base",
        "project_root": "..",
    },
    "knowledge_system": {
        "mcp_server": {
            "name": "ki-manager",
            "version": "2.0.0"
        }
    },
    "required_sections": ["Purpose", "Key Components", "Related KIs"]
}

OVERVIEW_KI_TEMPLATE = """\
# _OVERVIEW — Project Overview

**Module**: `{project_name}` (entire project)
**Last verified**: {date}

## Purpose

<!-- Describe the project's main purpose here -->

## Key Components

<!-- List the main subsystems or modules -->

## Entry Points

<!-- Describe main entry points (CLI commands, API endpoints, etc.) -->

## Architecture Notes

<!-- Key architectural decisions, constraints, patterns used -->

## Related KIs

<!-- Links to other KI files will appear here -->
"""

DIR_INDEX_TEMPLATE = """\
# DIR_INDEX.md — Directory Index

*Auto-generated by ki-manager. Re-generate with `generate_dir_index` tool.*

| Directory | Purpose | KI |
|-----------|---------|-----|
"""

DOC_CONFIG_TEMPLATE = {
    "project_name": "{project_name}",
    "knowledge_items": {
        "_OVERVIEW.ki.md": {
            "summary": "Project overview",
            "modules": []
        }
    },
    "coverage_settings": {
        "tracked_modules": []
    }
}


# ─── Helpers ─────────────────────────────────────────────────────────────────

def detect_venv(root_dir: Path) -> str:
    """Detect venv Python executable in the project."""
    for name in [".venv", "venv", "env"]:
        for subpath in [("Scripts", "python.exe"), ("bin", "python")]:
            py = root_dir / name / Path(*subpath)
            if py.exists():
                return str(py)
    return ""


def write_json(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)


def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def update_gitignore(project_root: Path):
    """Append .ki-base/config.json to the project .gitignore if not already present."""
    gitignore = project_root / ".gitignore"
    line = ".ki-base/config.json"
    if gitignore.exists():
        content = gitignore.read_text(encoding="utf-8")
        if line in content:
            return
        with open(gitignore, "a", encoding="utf-8") as f:
            f.write(f"\n# ki-manager — machine-specific (do not commit)\n{line}\n")
    else:
        write_text(gitignore, f"# ki-manager — machine-specific (do not commit)\n{line}\n")


def _format_template(template, **kwargs) -> dict:
    """Recursively format string values in a dict template."""
    if isinstance(template, dict):
        return {k: _format_template(v, **kwargs) for k, v in template.items()}
    if isinstance(template, str):
        return template.format(**kwargs)
    return template


# ─── Main Tool ────────────────────────────────────────────────────────────────

def init_project(args: dict) -> str:
    """
    ki_init_project tool implementation.
    """
    raw_path = args.get("project_path", "")
    if not raw_path:
        return "Error: project_path is required."

    project_path = Path(ki_utils.normalize_path(raw_path))
    if not project_path.exists():
        return f"Error: project_path does not exist: {project_path}"

    project_name = args.get("project_name") or project_path.name
    language = args.get("language", "python")
    venv_python = args.get("venv_python") or detect_venv(project_path)
    force = args.get("force", False)
    know_name = args.get("knowledge_root", ".ki-base")
    cfg_loc = args.get("config_location", "knowledge_dir")

    ki_base = project_path / know_name
    knowledge_dir = ki_base / "knowledge"
    log = []

    knowledge_dir.mkdir(parents=True, exist_ok=True)
    log.append(f"[+] Created {know_name}/ structure at: {ki_base}")

    config_json_path = ki_base / "config.json"
    if not config_json_path.exists() or force:
        config_data = {
            "server_version": "2.0.0",
            "registered_at": datetime.now().isoformat(),
            "project_name": project_name,
            "venv_python": venv_python,
            "exclude_patterns": ["node_modules", ".venv", "venv", "__pycache__", ".git", "dist", "build"]
        }
        write_json(config_json_path, config_data)
        log.append(f"[+] Created {know_name}/config.json (machine-specific)")
    else:
        log.append(f"[~] {know_name}/config.json already exists")

    ki_config_path = project_path / "ki_config.json" if cfg_loc == "root" else ki_base / "ki_config.json"
    if not ki_config_path.exists() or force:
        data = _format_template(KI_CONFIG_TEMPLATE, project_name=project_name, language=language)
        if know_name != ".ki-base":
            if "paths" not in data:
                data["paths"] = {}
            data["paths"]["knowledge_root"] = know_name
        write_json(ki_config_path, data)
        log.append(f"[+] Created {ki_config_path.relative_to(project_path)}")
    else:
        log.append(f"[~] {ki_config_path.relative_to(project_path)} already exists")

    doc_config_path = ki_base / "doc_config.json"
    if not doc_config_path.exists() or force:
        doc_config_data = _format_template(DOC_CONFIG_TEMPLATE, project_name=project_name)
        write_json(doc_config_path, doc_config_data)
        log.append(f"[+] Created {know_name}/doc_config.json")

    dir_index_path = ki_base / "DIR_INDEX.md"
    if not dir_index_path.exists() or force:
        write_text(dir_index_path, DIR_INDEX_TEMPLATE)
        log.append(f"[+] Created {know_name}/DIR_INDEX.md")

    overview_path = knowledge_dir / "_OVERVIEW.ki.md"
    if not overview_path.exists() or force:
        today = datetime.now().strftime("%Y-%m-%d")
        write_text(overview_path, OVERVIEW_KI_TEMPLATE.format(project_name=project_name, date=today))
        log.append(f"[+] Created {know_name}/knowledge/_OVERVIEW.ki.md")

    if cfg_loc != "root":
        update_gitignore(project_path)
    
    success, msg = ki_utils.register_project(config_path=str(ki_config_path), workspace=str(project_path))
    if success:
        log.append(f"[+] {msg}")
    else:
        log.append(f"[!] Registry: {msg}")

    log.append("")
    log.append("✓ Initialization complete.")
    log.append(f"  Connect MCP server: ki-manager --workspace {project_path}")
    return "\n".join(log)

def migrate_project(project_root: str) -> str:
    """Migrate an old ki-global-server project to ki-manager 2.x standard."""
    root = Path(project_root)
    log = []

    legacy_dir = root / ".know"
    new_dir = root / ".ki-base"

    # 1. Rename directory if needed
    if legacy_dir.exists() and not new_dir.exists():
        try:
            legacy_dir.rename(new_dir)
            log.append(f"[+] Renamed .know/ to .ki-base/")
        except Exception as e:
            return f"Error renaming .know to .ki-base: {e}"
    elif not new_dir.exists():
        return "No .know/ or .ki-base/ found. Run ki_init_project instead."
    else:
        log.append(f"[~] .ki-base/ already exists.")

    # 2. Update doc_config.json
    doc_config_path = new_dir / "doc_config.json"
    if doc_config_path.exists():
        try:
            with open(doc_config_path, "r", encoding="utf-8") as f:
                config = json.load(f)
            
            changed = False
            if "paths" in config:
                if config["paths"].get("knowledge_root") == ".know":
                    config["paths"]["knowledge_root"] = ".ki-base"
                    changed = True
                if "agent_instructions" in config["paths"]:
                    del config["paths"]["agent_instructions"]
                    changed = True
            
            if changed:
                with open(doc_config_path, "w", encoding="utf-8") as f:
                    json.dump(config, f, indent=2, ensure_ascii=False)
                log.append("[+] Updated doc_config.json (paths migrated)")
            else:
                log.append("[~] doc_config.json already up to date")
        except Exception as e:
            log.append(f"[!] Error updating doc_config.json: {e}")

    # 3. Preserve AGENTS.md (no longer forcibly deleted)
    agents_md = new_dir / "AGENTS.md"
    if agents_md.exists():
        log.append("[~] Preserved existing AGENTS.md")

    # 4. Create _OVERVIEW.ki.md if missing
    knowledge_dir = new_dir / "knowledge"
    knowledge_dir.mkdir(exist_ok=True)
    overview_path = knowledge_dir / "_OVERVIEW.ki.md"
    if not overview_path.exists():
        try:
            today = datetime.date.today().isoformat()
            project_name = root.name
            if doc_config_path.exists():
                try:
                    with open(doc_config_path, "r", encoding="utf-8") as f:
                        project_name = json.load(f).get("project_name", project_name)
                except Exception:
                    pass
            
            write_text(overview_path, OVERVIEW_KI_TEMPLATE.format(project_name=project_name, date=today))
            log.append("[+] Created missing _OVERVIEW.ki.md")
        except Exception as e:
            log.append(f"[!] Error creating _OVERVIEW.ki.md: {e}")
    else:
        log.append("[~] _OVERVIEW.ki.md already exists")

    return "\n".join(log)
