"""
scaffold.py

Tool: ki_init_project
Creates .ki-base/ structure in a target project directory,
then registers the project in the global KI registry.

Created structure:
  <project_root>/
  └── .ki-base/
      ├── config.json        ← machine-specific (added to .gitignore)
      ├── ki_config.json     ← project settings (in git)
      ├── doc_config.json    ← file→KI mapping (in git)
      ├── AGENTS.md          ← instructions for AI agents (in git)
      ├── DIR_INDEX.md       ← directory index (in git)
      └── knowledge/
          └── _OVERVIEW.ki.md  ← starter KI (in git)
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Allow import of ki_utils from sibling scripts/ directory
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts"))
import ki_utils


# ─── Templates ────────────────────────────────────────────────────────────────

AGENTS_MD_TEMPLATE = """\
# AGENTS.md — AI Agent Instructions for {project_name}

This file is auto-managed by **ki-manager**. Do not delete.

## Navigation

All Knowledge Items (KI) live in `.ki-base/knowledge/`.
Start here: `.ki-base/knowledge/_OVERVIEW.ki.md`

## KI Table

| File | Summary |
|------|---------|

## Rules

- Always read relevant KIs before modifying a module.
- After significant changes, run `audit_coverage` via MCP.
- Use `git_checkpoint` to save knowledge snapshots.
"""

DIR_INDEX_TEMPLATE = """\
# DIR_INDEX.md — Directory Index

*Auto-generated by ki-manager. Re-generate with `generate_dir_index` tool.*

| Directory | Purpose | KI |
|-----------|---------|-----|
"""

OVERVIEW_KI_TEMPLATE = """\
# _OVERVIEW — Project Overview

**Module**: `{project_name}` (entire project)
**Last verified**: {date}

## Purpose

<!-- Describe the project's main purpose here -->

## Key Components

<!-- List the main subsystems or modules -->

## Entry Points

<!-- Describe main entry points -->

## Related KIs

<!-- Links to other KI files will appear here -->
"""

KI_CONFIG_TEMPLATE = {
    "project_name": "{project_name}",
    "language": "{language}",
    "doc_style": "ki-v2",
    "auto_resolve": True,
    "paths": {
        "knowledge_root": ".ki-base",
        "project_root": "..",
        "agent_instructions": "AGENTS.md",
    },
    "knowledge_system": {
        "mcp_server": {
            "name": "ki-manager",
            "version": "2.0.0"
        }
    },
    "required_sections": ["Purpose", "Key Components", "Related KIs"]
}

DOC_CONFIG_TEMPLATE = {
    "project_name": "{project_name}",
    "knowledge_items": {
        "_OVERVIEW.ki.md": {
            "summary": "Project overview",
            "modules": []
        }
    },
    "coverage_settings": {
        "tracked_modules": []
    }
}


# ─── Helpers ─────────────────────────────────────────────────────────────────

def detect_venv(root_dir: Path) -> str:
    """Detect venv Python executable in the project."""
    for name in [".venv", "venv", "env"]:
        for subpath in [("Scripts", "python.exe"), ("bin", "python")]:
            py = root_dir / name / Path(*subpath)
            if py.exists():
                return str(py)
    return ""


def write_json(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)


def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def update_gitignore(project_root: Path):
    """Append .ki-base/config.json to the project .gitignore if not already present."""
    gitignore = project_root / ".gitignore"
    line = ".ki-base/config.json"
    if gitignore.exists():
        content = gitignore.read_text(encoding="utf-8")
        if line in content:
            return
        with open(gitignore, "a", encoding="utf-8") as f:
            f.write(f"\n# ki-manager — machine-specific (do not commit)\n{line}\n")
    else:
        write_text(gitignore, f"# ki-manager — machine-specific (do not commit)\n{line}\n")


def _format_template(template, **kwargs) -> dict:
    """Recursively format string values in a dict template."""
    if isinstance(template, dict):
        return {k: _format_template(v, **kwargs) for k, v in template.items()}
    if isinstance(template, str):
        return template.format(**kwargs)
    return template


# ─── Main Tool ────────────────────────────────────────────────────────────────

def init_project(args: dict) -> str:
    """
    ki_init_project tool implementation.
    args:
      - project_path (required): absolute path to project root
      - project_name (optional): defaults to folder name
      - language (optional): 'python', 'typescript', etc. Defaults to 'python'
      - venv_python (optional): explicit path to venv python
      - force (optional): overwrite existing files if True
    """
    raw_path = args.get("project_path", "")
    if not raw_path:
        return "Error: project_path is required."

    project_path = Path(ki_utils.normalize_path(raw_path))
    if not project_path.exists():
        return f"Error: project_path does not exist: {project_path}"

    project_name = args.get("project_name") or project_path.name
    language = args.get("language", "python")
    venv_python = args.get("venv_python") or detect_venv(project_path)
    force = args.get("force", False)

    ki_base = project_path / ".ki-base"
    knowledge_dir = ki_base / "knowledge"
    log = []

    # ── Create directories ──
    knowledge_dir.mkdir(parents=True, exist_ok=True)
    log.append(f"[+] Created .ki-base/ structure at: {ki_base}")

    # ── config.json (machine-specific) ──
    config_json_path = ki_base / "config.json"
    if not config_json_path.exists() or force:
        config_data = {
            "server_version": "2.0.0",
            "registered_at": datetime.now().isoformat(),
            "project_name": project_name,
            "venv_python": venv_python,
            "exclude_patterns": ["node_modules", ".venv", "venv", "__pycache__", ".git", "dist", "build"]
        }
        write_json(config_json_path, config_data)
        log.append(f"[+] Created .ki-base/config.json (machine-specific, in .gitignore)")
    else:
        log.append(f"[~] .ki-base/config.json already exists, skipping")

    # ── ki_config.json (in git) ──
    ki_config_path = ki_base / "ki_config.json"
    if not ki_config_path.exists() or force:
        ki_config_data = _format_template(KI_CONFIG_TEMPLATE, project_name=project_name, language=language)
        write_json(ki_config_path, ki_config_data)
        log.append(f"[+] Created .ki-base/ki_config.json")
    else:
        log.append(f"[~] .ki-base/ki_config.json already exists, skipping")

    # ── doc_config.json (in git) ──
    doc_config_path = ki_base / "doc_config.json"
    if not doc_config_path.exists() or force:
        doc_config_data = _format_template(DOC_CONFIG_TEMPLATE, project_name=project_name)
        write_json(doc_config_path, doc_config_data)
        log.append(f"[+] Created .ki-base/doc_config.json")
    else:
        log.append(f"[~] .ki-base/doc_config.json already exists, skipping")

    # ── AGENTS.md (in git) ──
    agents_path = ki_base / "AGENTS.md"
    if not agents_path.exists() or force:
        write_text(agents_path, AGENTS_MD_TEMPLATE.format(project_name=project_name))
        log.append(f"[+] Created .ki-base/AGENTS.md")
    else:
        log.append(f"[~] .ki-base/AGENTS.md already exists, skipping")

    # ── DIR_INDEX.md (in git) ──
    dir_index_path = ki_base / "DIR_INDEX.md"
    if not dir_index_path.exists() or force:
        write_text(dir_index_path, DIR_INDEX_TEMPLATE)
        log.append(f"[+] Created .ki-base/DIR_INDEX.md")
    else:
        log.append(f"[~] .ki-base/DIR_INDEX.md already exists, skipping")

    # ── _OVERVIEW.ki.md (in git) ──
    overview_path = knowledge_dir / "_OVERVIEW.ki.md"
    if not overview_path.exists() or force:
        today = datetime.now().strftime("%Y-%m-%d")
        write_text(overview_path, OVERVIEW_KI_TEMPLATE.format(project_name=project_name, date=today))
        log.append(f"[+] Created .ki-base/knowledge/_OVERVIEW.ki.md")
    else:
        log.append(f"[~] .ki-base/knowledge/_OVERVIEW.ki.md already exists, skipping")

    # ── .gitignore ──
    update_gitignore(project_path)
    log.append(f"[+] Added .ki-base/config.json to .gitignore")

    # ── Register in global registry ──
    success, msg = ki_utils.register_project(str(ki_config_path))
    if success:
        log.append(f"[+] {msg}")
    else:
        log.append(f"[!] Registry: {msg}")

    log.append("")
    log.append("✓ Initialization complete.")
    log.append(f"  Connect MCP server: uvx ki-manager --workspace {project_path}")
    return "\n".join(log)
