"""
generate_dir_index.py

Generates DIR_INDEX.md — a compact project directory tree
(only folders + file count in each, no file names).
"""

import os
import sys
import argparse
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ki_utils

KNOWLEDGE_ROOT = ki_utils.KNOWLEDGE_ROOT

EXCLUDED_DIRS = {
    ".git", "__pycache__", "node_modules", "venv", ".venv",
    "dist", "build", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "coverage", ".next", "out",
}


def count_files_in_dir(dirpath: str) -> int:
    total = 0
    for root, dirs, files in os.walk(dirpath):
        dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS]
        total += len(files)
    return total


def build_tree(root: str, knowledge_root_name: str,
               prefix: str = "", max_depth: int = 3, current_depth: int = 0) -> list:
    if current_depth > max_depth:
        return []
    lines = []
    try:
        entries = sorted(os.listdir(root))
    except PermissionError:
        return []

    # Show hidden dirs only if they're the knowledge root or .agent
    show_hidden = {".agent", knowledge_root_name}
    dirs = [
        e for e in entries
        if os.path.isdir(os.path.join(root, e))
        and e not in EXCLUDED_DIRS
        and (not e.startswith(".") or e in show_hidden)
    ]

    for i, dirname in enumerate(dirs):
        is_last = (i == len(dirs) - 1)
        connector = "`-- " if is_last else "|-- "
        child_path = os.path.join(root, dirname)
        file_count = count_files_in_dir(child_path)
        count_label = f"  *{file_count} files*" if file_count > 0 else "  *(empty)*"
        lines.append(f"{prefix}{connector}{dirname}/{count_label}")

        extension = "    " if is_last else "|   "
        child_lines = build_tree(
            child_path, knowledge_root_name,
            prefix=prefix + extension,
            max_depth=max_depth,
            current_depth=current_depth + 1
        )
        lines.extend(child_lines)
    return lines


def generate_dir_index(project_root: str, output_path: str,
                        knowledge_root_name: str, max_depth: int = 3) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    project_name = os.path.basename(os.path.abspath(project_root))
    total_files = count_files_in_dir(project_root)
    tree_lines = build_tree(project_root, knowledge_root_name, max_depth=max_depth)

    content_lines = [
        f"# DIR_INDEX — {project_name}",
        "",
        "> Compact directory tree for AI agent onboarding.",
        f"> Only folders are shown (depth up to {max_depth}). Files are not included.",
        "> Automatically updated when running `/sync-knowledge`.",
        "",
        f"**Total files in project:** ~{total_files} (excluding excluded directories)",
        f"**Updated:** {now}",
        "",
        "```",
        f"{project_name}/",
    ] + tree_lines + [
        "```",
        "",
        "## Key Directory Purposes",
        "",
        "| Directory | Purpose |",
        "|---|---|",
        f"| `{knowledge_root_name}/` | Knowledge system: KI files, workflows, scripts |",
        f"| `{knowledge_root_name}/knowledge/` | KI files for AI agents |",
        f"| `{knowledge_root_name}/decisions/` | Architectural Decision Records (ADR) |",
        "",
        "---",
        f"*Generated by: `{knowledge_root_name}/scripts/generate_dir_index.py`*",
    ]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content_lines) + "\n")

    print(f"[+] DIR_INDEX.md generated: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generates DIR_INDEX.md.")
    parser.add_argument("--root", default=".", help="Project root directory")
    parser.add_argument("--output", default=None, help="Output path for DIR_INDEX.md")
    parser.add_argument("--depth", type=int, default=3, help="Maximum depth (default: 3)")
    args = parser.parse_args()

    project_root = os.path.abspath(args.root)
    knowledge_root_name = os.path.basename(KNOWLEDGE_ROOT) if KNOWLEDGE_ROOT else ".know"

    know_dir = KNOWLEDGE_ROOT if os.path.isabs(KNOWLEDGE_ROOT) \
        else os.path.join(project_root, KNOWLEDGE_ROOT)
    output_path = args.output or os.path.join(know_dir, "DIR_INDEX.md")
    output_path = os.path.abspath(output_path)

    generate_dir_index(project_root, output_path, knowledge_root_name, max_depth=args.depth)


if __name__ == "__main__":
    if sys.platform == "win32":
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8")
    main()
